sudo: false

language: node_js
node_js:
  # - "4"
  # - "6"
  # - "8"
  - "10"

os:
  - osx
  # - linux

branches:
  except:
    - gh-pages

install:
  - node --version
  - npm --version
  - npm install

before_script:
- git config --global user.name 'genthaler'
- git config --global user.email 'genthaler@users.noreply.github.com'
- git remote set-url origin "https://${GH_TOKEN}@github.com/genthaler/elm-grid-war.git"

script:
  - npm test

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
env:
 global:
 - GH_REF: github.com/genthaler/elm-grid-war.git
 - secure: 
