sudo: false

language: node_js
node_js:
  # - "4"
  # - "6"
  # - "8"
  - "10"

os:
  - osx
  # - linux

branches:
  except:
    - gh-pages

install:
  - node --version
  - npm --version
  - npm install

before_script:
- git config --global user.name 'genthaler'
- git config --global user.email 'genthaler@users.noreply.github.com'
- git remote set-url origin "https://${GH_TOKEN}@github.com/genthaler/elm-grid-war.git"

script:
  - npm test
  - npm run deploy

env:
  global:
  - GH_REF: github.com/genthaler/elm-grid-war.git
  - GITHUB_REPO: genthaler/elm-grid-war
  - secure: ${GITHUB-TOKEN}
